name: Build NSIS Installer

on:
  release:
    types: [published]

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the public repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set release variables
      - name: Set release variables
        run: |
          echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "RELEASE_ZIP=CB-${GITHUB_REF##*/}.zip" >> $GITHUB_ENV
          echo "RELEASE_FOLDER=CB-${GITHUB_REF##*/}" >> $GITHUB_ENV

      # Step 3: Download the release zip attached to this public release
      - name: Download release asset
        uses: dawidd6/fetch-gh-release-asset@v1
        with:
          repo: ${{ github.repository }}
          version: ${{ github.event.release.tag_name }}
          file: ${{ env.RELEASE_ZIP }}

      # Step 4: Extract the zip
      - name: Extract zip
        run: Expand-Archive -Path ${{ env.RELEASE_ZIP }} -DestinationPath .

      # Step 5: Install NSIS
      - name: Install NSIS
        run: choco install nsis -y

      # Step 6: Build NSIS installer
      - name: Build NSIS installer
        run: |
          makensis /DAPPVER=${{ env.RELEASE_TAG }} /DReleaseFolder=${{ env.RELEASE_FOLDER }} installer.nsi

      # Step 7: Upload installer to release
      - name: Upload installer to public release
        uses: softprops/action-gh-release@v2
        with:
          files: installer_ChoppingBoard_${{ env.RELEASE_TAG }}.exe
